prowjob_namespace: default
pod_namespace: test-pods
log_level: debug
periodics: 
  - name: periodic-job
    agent: kubernetes
    interval: 10m
    spec: 
      containers: 
        - image: alpine
          command: 
            - /bin/date          
postsubmits: 
  dzahariev/go-with-prow: 
  - name: post-submit-job
    agent: kubernetes
    max_concurrency: 10
    branches: 
    - ^master$
    skip_branches: 
     - ^rel-.*$
    spec: 
      containers: 
      - image: alpine
        command: 
         - /bin/date
presubmits: 
  dzahariev/go-with-prow: 
  - name: pre-submit-job
    agent: kubernetes
    max_concurrency: 10
    always_run: true
    skip_report: false
    branches: []
    skip_branches: []
    spec: 
        containers: 
        - image: golang:alpine
          command: ["/bin/sh","-c"]
          args:
           - echo "update"; apk update; echo "upgrade"; apk upgrade; echo "install git"; apk add --no-cache git openssh build-base gcc abuild binutils; echo "checkout repo"; go get github.com/$(REPO_OWNER)/$(REPO_NAME); echo "navigate to source"; cd /go/src/github.com/$(REPO_OWNER)/$(REPO_NAME); echo "fetch"; git fetch origin pull/$(PULL_NUMBER)/head:pr_$(PULL_NUMBER); echo "checkout the PR"; git checkout pr_$(PULL_NUMBER); echo "execute tests"; go test ./...;
plank:
  job_url_prefix_config:
    ‘*’: http://192.168.64.77:30250/
  job_url_template: http://192.168.64.77:30250/log?job={{.Spec.Job}}&id={{.Status.BuildID}}’
